
import type { Metadata } from "next";
import { useState } from "react";
import Link from 'next/link'
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
      <div style={{ height: "100px", background: "red"}}>
        <div>
      <Link href="/portfolio">Portfolio</Link>
      <Link href="/dashboard/analytics">analytics</Link>
      <Link href="/dashboard/settings/profile">profile</Link>
      <Link href="/dashboard/settings/password">password</Link>
        </div>
      <div>
        <Navbar />
      </div>
      </div>
      {children}
      </body>
     
      
    </html>
  );
}
